export enum EndpointType {
  TASK_GET_ALL = "/task/all",
  TASK_GET_BY_ID = "/task/byId",
  TASK_NEW = "/task/new",
  TASK_UPDATE = "/task/update",
  TASK_DELETE = "/task/delete",
  TASK_ADD_DEPENDENCY = "/task/add_dependency",
  TASK_REMOVE_DEPENDENCY = "/task/remove_dependency",
  TASK_ASSIGN_USER = "/task/assign",
  TASK_UNASSIGN_USER = "/task/unassign",
  TASK_ADD_TAG = "/task/add_tag",
  TASK_REMOVE_TAG = "/task/remove_tag",
  TASK_ADD_UPDATE = "/task/add_update",
  TASK_REMOVE_UPDATE = "/task/remove_update",
  TASK_UPDATE_TASK_UPDATE = "/task/update_tu",

  USER_GET_ALL = "/user/all",
  USER_GET_BY_ID = "/user/byId",
  USER_NEW = "/user/new",
  USER_UPDATE = "/user/update",
  USER_DELETE = "/user/delete",
  USER_LOGIN = "/user/login",
  USER_REGISTER = "/user/register",
  USER_MEMBER = "/user/workspaces",

  WORKSPACE_GET_ALL = "/workspace/all",
  WORKSPACE_GET_BY_ID = "/workspace/byId",
  WORKSPACE_NEW = "/workspace/new",
  WORKSPACE_UPDATE = "/workspace/update",
  WORKSPACE_DELETE = "/workspace/delete",
  WORKSPACE_ADD_USER = "/workspace/add_user",
  WORKSPACE_REMOVE_USER = "/workspace/remove_user",
  WORKSPACE_ADD_MOD = "/workspace/add_mod",
  WORKSPACE_REMOVE_MOD = "/workspace/remove_mod",
}
